# fly.toml app configuration file generated for leddit on 2023-12-15T15:51:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "leddit"
kill_signal = "SIGINT"
kill_timeout = 5
# mounts = []
primary_region = "ord"
processes = []

[build]
[build.args]
NODE_VERSION = "18.18.2"
PHP_VERSION = "8.2"

[env]
APP_ENV = "production"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
DB_CONNECTION = "mysql"
DB_HOST = "aws.connect.psdb.cloud"
DB_PORT = 3306
DB_DATABASE = "leddit"
MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
